### ISSUE TITLE
Same issue as #16 Closed "As soon as I select an avatar my triggers stop working"

### ISSUE THREAD

**Issue by Tutlek** [nicoco007/DynamicOpenVR#20] opened 2020-02-19 20:50 UTC
As soon as I select an avatar my triggers stop working
Exactly same issue as #16 Closed but on Rift S steamvr.
If i start in native oculus mode it works fine but i don't use native its horrible performance.

Hands still track but I cant seem to select anything in game. I tried binding right trigger pull to another button but that didn't work
Blue laser is stuck in one hand and cant switch. The menu icons still highlight when I point at them.

-win 10
-Oculus Rift S
[_latest.log](https://github.com/nicoco007/DynamicOpenVR/files/4227312/_latest.log)

Ty

**Comment by nicoco007** [comment] 2020-02-20 07:16
Could you try [this build](https://ci.gnyra.com/job/DynamicOpenVR/job/master/114/artifact/DynamicOpenVR.BeatSaber-1834c18-RELEASE.zip) and let me know if it works? If it doesn't, could you attach your latest log running that version?

**Comment by Tutlek** [comment] 2020-02-20 19:35
Now tracking is disabled,nothing works.Hands don't move.Cant get past starting screen where i need to click continue.
In native mode( -vrmode oculus) works fine except i don't want to use it,horrible performance. 
I did try few old combinations and Version 0.1.0 beta 4 + one of old custom avatar(back from 1.6bs) works...
I really would like new versions to work...using old ones for now.
Log is from version u posted.
[_latest.log](https://github.com/nicoco007/DynamicOpenVR/files/4232612/_latest.log)
Ty for help.

**Comment by nicoco007** [comment] 2020-02-20 21:52
Could you run [this build](https://ci.gnyra.com/job/DynamicOpenVR/job/master/119/artifact/DynamicOpenVR.BeatSaber-3cd3bd9-RELEASE.zip) (it probably won't fix anything but will give me some more information on what's going on) and then attach:
* Your latest log
* The file `DynamicOpenVR\Actions\beatsaber.json`
* The file `DynamicOpenVR\action_manifest.json`

You can put them all in a ZIP since GitHub doesn't allow uploading `.json` files.

**Comment by Tutlek** [comment] 2020-02-21 18:01
Aye,same as before.
Tracking is disabled,nothing works.Hands don't move.Cant get past starting screen where i need to click continue on health care xD

[log-jsons.zip](https://github.com/nicoco007/DynamicOpenVR/files/4237386/log-jsons.zip)

Hope it helps
Ty

**Comment by RincewindUK** [comment] 2020-02-22 17:48
im having the exact same issue with my vive setup, the controller buttons stop working when picking an avatar, it keeps changing the control scheme to some legacy thing and doesnt let me change it back to default.

attached my log files

[DynamicOpenVR.zip](https://github.com/nicoco007/DynamicOpenVR/files/4239708/DynamicOpenVR.zip)

**Comment by Tutlek** [comment] 2020-02-22 19:01
> 
> 
> im having the exact same issue with my vive setup, the controller buttons stop working when picking an avatar, it keeps changing the control scheme to some legacy thing and doesnt let me change it back to default.
> 
> attached my log files
> 
> [DynamicOpenVR.zip](https://github.com/nicoco007/DynamicOpenVR/files/4239708/DynamicOpenVR.zip)

Solution for Vive is under Closed issue 16# ,check it out.

**Comment by nicoco007** [comment] 2020-03-11 22:11
I'm unfortunately still unsure as to what's going on, but I'll be releasing a new version of Custom Avatars in the next few days that'll make DynamicOpenVR optional and should therefore fix this issue.

**Comment by nicoco007** [comment] 2020-07-20 00:29
Closing since the root cause of this issue is now isolated in DynamicOpenVR.BeatSaber which shouldn't be installed when using Oculus headsets (at least for the time being).

**Closed as completed by nicoco007** 2020-07-20 00:29 UTC
Labels: bug
